### ISSUE TITLE
New features, but problem with the marge. 

### ISSUE THREAD

**Issue by yupihello** [NicoleFaye/Chat-Gpt-Long-Text-Input#19]
Hello, first of all congratulations for your effort, this plugin is really useful. Second, I have made improvements to the plugin in terms of adding the option to save the response to a json or txt file, with a icon. I improved the division of the input text by sentence, and that it does not break any sentence before the indicated maximum of words. Also add responsive functions new "continue generating" feature allowing to expand input maximum size to 12000 words. And add the function of recognizing some errors reported by the server and, if applicable, clicking on the regenerate response button. I have also seen that in some moments chat.openai.com/ has decided to hide the "regenerate response" button that is a pillar for the code, so I thought that in the future we should explore a new mechanism for the automation of messages. I use it especially to summarize text. I only have a problem I did not follow an order when making the improvements and I am afraid that if I publish it in the fork it will not match either in main or in dev. I thought about rewriting my proposal based on your last stable line so that it matches and you can join them. Or based on your latest development version. I only modified the plugin for Firefox. Apologies in advance for the translation of the text since I do not speak English well.

**Comment by NicoleFaye** [comment]
I am feeling pretty sick this week. I will take a look at your fork when I am feeling better. Glad you find the project useful :)

**Comment by yupihello** [comment]
Hello, hoping you are well, and better health soon. I tell you that just a few days after I wrote to you, they modified the frontend of chat.openai.com. They seem to have a method to detect the handleKeyDown, handleKeyPress, and handleKeyUp functions that are generated by the browser. It's probably through an environment like React.js checking if the isTrusted property is false. So in our latest versions, you can still write the text replacing the content of the textarea, but the "Send message" button is not activated, nor can you send messages through the "Enter" key if it does not detect human typing. I have explored some solutions but still can't get past this limitation. I think an alternative can be to migrate to the ChatGPTBox method that works in the background by capturing the responses and sending the messages, using the information from the cookies. I'll keep digging a bit more, as it's interesting to be able to improve the plugin according to the original design.

**Comment by NicoleFaye** [comment]
I think i have a working version on firefox-main going to start testing chrome.

**Comment by NicoleFaye** [comment]
Okay I think its working now on both version. 

I'm recovering and still plan to take a look at your fork when I am back to 100%. I just wanted to make sure the plugin is functional in its current state. Thank you for the heads up on the frontend changes.

**Comment by NicoleFaye** [comment]
Okay so I tried taking a look at your fork but I can't seem to find the changes you made. Can you link me to the file that has the changes?

**Comment by yupihello** [comment]
Sorry I haven't had time these days, I hope to upload the content before the weekend.

**Comment by NicoleFaye** [comment]
Any update on this?

**Comment by NicoleFaye** [comment]
I am going to close this issue for now. Feel free to reopen it when your code is uploaded if you want and I will take a look.
