### ISSUE TITLE
SUggestion - add Text to end of each part

### ISSUE THREAD

**Issue by Windows200000** [NicoleFaye/Chat-Gpt-Long-Text-Input#2]
I found that the only consistent way to stop chatgpt from trying to continue a text is to add something to the end, like `(end of part)`.

**Comment by NicoleFaye** [comment]
@Windows200000 I have plans to add settings so you can set that to be what you want and use custom prompts and modify the message chunk size. 

I just finished my last final so I'll probably add this in the next week or two.

What I have done to get it to stop trying to complete is telling it to reply with only the word "confirmed", when it's in quotes it seems to be more consistent.

All in all the prompts definitely need modification. And I can definitely add a section to be appended after each section . 😊
