### ISSUE TITLE
Issue on updating text

### ISSUE THREAD

**Issue by roarast** [NicoleFaye/Chat-Gpt-Long-Text-Input#27]
Firstly I wanted to say this was a great add-on, I have found it really useful.
However recently something seems to not be working.  The first prompt works and is entered in to ChatGPT, it returns confirmed.
However then is stalls and stops, not more text is entered.
Is there a problem with an update, firefox, chatgpt or the add on.?

**Comment by roarast** [comment]
I think the issue is the add-on is looking from "regenerate response" and the interface has changed so this is no only "regenerate"

**Comment by roarast** [comment]
*now

**Comment by NicoleFaye** [comment]
This is 100% correct Im going to push a fix now. Thank you for creating this issue!

**Comment by NicoleFaye** [comment]
Fix is now published on firefox webstore. Chrome webstore will update sometime in the next 24 hrs, their review process is a little longer.

**Comment by roarast** [comment]
Great, many thanks for fixing this, it is working fine again now.  Much appreciated.
