### ISSUE TITLE
Feature requests - Progress-related features

### ISSUE THREAD

**Issue by dancrew32** [NicoleFaye/Chat-Gpt-Long-Text-Input#30]
First off, incredible work on this extension. Thanks!

Just adding some feature requests here because when you're trying to add a very large corpus of text, it would be very helpful to know a few things:

1. The percentage completion (number of inputs / total number of inputs)
2. The ETA (hours/mins/seconds best guess given the current rate)
3. An alert based on the input that the user should switch from GPT4 to GPT3.5, because there's some throttling on inputs for GPT4. Or a special input rate limiter that allows the user to maintain the use of GPT4 for an extended-length input.

**Comment by NicoleFaye** [comment]
I will see what I can do :)

**Comment by NicoleFaye** [comment]
For now, the newest version displays how many messages you can expect to generate before you hit send and shows the current progress on the page for how many messages have been sent in the format {messages sent} / {total messages} .

I can definitely add an eta as well in the next version. I am not sure I will do the alert about gpt4/3.5 and will just leave that up to the user to manage based off the number of messages expected before starting a job.

**Comment by NicoleFaye** [comment]
Okay, version 1.5.1 adds the time based estimate.
