### ISSUE TITLE
If I want to increase functionality and scope 

### ISSUE THREAD

**Issue by CharlyWNot** [NicoleFaye/Chat-Gpt-Long-Text-Input#51]
Hi Nicole, 
I love the concept, but as said it is competing with a lot of other interfering extensions. 
I wonder if I can get your insight about using this differently. Is there a way to communicate privately?

~in Latin~

this is an email that I used with my band years ago, doesn't mean anything :) but I know is not great :)
latinfunk44@gmail.com

**Comment by NicoleFaye** [comment]
sent you an email
