### ISSUE TITLE
problem extension

### ISSUE THREAD

**Issue by funmolde** [NicoleFaye/Chat-Gpt-Long-Text-Input#54]
Hello -_-  , the extension does not send Before each addition and Text to import.
I made a little video , I tried to deactivate my ad blocker but nothing changes.

I don't have these settings;
https://raw.githubusercontent.com/NicoleFaye/Chat-Gpt-Long-Text-Input/Firefox-Main/screencaps/settingsPage.png

Info:
edge browser latest version
windows 11 64 bit

Thanks You -_-

https://github.com/NicoleFaye/Chat-Gpt-Long-Text-Input/assets/13144261/a1cde1aa-2fe2-4682-9a21-2f330684003b

**Comment by NicoleFaye** [comment]
How did you install this? I dont officially support edge but its technically chromium so it should work in theory, Ill see if i can reproduce what youre seeing.

**Comment by NicoleFaye** [comment]
It looks like you have an older version installed, are you able to see what version of the extension you have?

**Comment by funmolde** [comment]
Thanks You it works 🐶, I had installed an old version , sorry for the inconvenience
