### ISSUE TITLE
More of a question then any problem

### ISSUE THREAD

**Issue by ForDefault** [NicoleFaye/Chat-Gpt-Long-Text-Input#55]
First and foremost, I want to say **thank you for your work in developing this addon**. 
I was hoping I could reach out to you for some guidance on breaking down its functionality to create a desktop application.

- One aspect I'm exploring is breaking down lengthy documents into individual paragraphs- with specific in depth prompts. So I can collect it like a dataset after downloading the conversation. Kind of like a conveyor belt system that I can leave running. 

- Additionally, I've been considering transitioning this addon into a WebExtensions-based desktop application to prevent browser strain in the loading. 

Any direction with decoding the base64 modules in the content script bundle.js for desktop application development would be greatly appreciated

**Comment by NicoleFaye** [comment]
I would not look at the bundle.js, thats a minimized version made from using webpack. Look at the source js.

[Extension popup](https://github.com/NicoleFaye/Chat-Gpt-Long-Text-Input/blob/Firefox-Main/popup/ChatGptLongTextInput.js)
[Injected Script](https://github.com/NicoleFaye/Chat-Gpt-Long-Text-Input/blob/Firefox-Main/content_scripts/ChatGptLongTextInputContentScript.js)
[String manipulation](https://github.com/NicoleFaye/Chat-Gpt-Long-Text-Input/blob/Firefox-Main/content_scripts/ChatGptLongTextInputSharedMethods.js)
